import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { BadgeCheck, Boxes, Check, ChevronDown, Clock3, Factory, Plus, Scissors, Truck, WashingMachine, X } from "lucide-react";
import { useState } from "react";

const todayInput = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Dhaka" }).format(new Date());
const displayDate = (value: Date | string | number) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Dhaka" }).format(new Date(value));
const number = (value: unknown) => new Intl.NumberFormat("en-IN").format(Number(value) || 0);
const dateTime = (value: Date | string | number) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Dhaka" }).format(new Date(value));

const moduleMeta = {
  attendance: { eyebrow: "Manpower", title: "Attendance", description: "Record the floor team’s daily presence without turning this into payroll.", icon: Clock3 },
  cutting: { eyebrow: "Fabric preparation", title: "Cutting", description: "Track cut quantity, fabric movement, and the first stage of every order.", icon: Scissors },
  printing: { eyebrow: "Optional stage", title: "DTF printing", description: "Track print output only for orders that actually require DTF.", icon: WashingMachine },
  qc: { eyebrow: "Quality gate", title: "Quality control", description: "Make passed, failed, and rework quantities visible before packing.", icon: BadgeCheck },
  packing: { eyebrow: "Finishing", title: "Packing", description: "Track packed quantities and keep delivery readiness accurate.", icon: Boxes },
  delivery: { eyebrow: "Dispatch", title: "Delivery", description: "Record partial and full deliveries against the real order quantity.", icon: Truck },
} as const;

type Module = keyof typeof moduleMeta;

function Header({ module, onNew, showNew = true }: { module: Module; onNew?: () => void; showNew?: boolean }) {
  const meta = moduleMeta[module];
  const Icon = meta.icon;
  return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow mb-2">{meta.eyebrow}</p><div className="flex items-center gap-3"><div className="metric-icon metric-teal"><Icon className="h-5 w-5" /></div><h1 className="font-display text-3xl tracking-tight text-[#163247] sm:text-4xl">{meta.title}</h1></div><p className="mt-2 max-w-2xl text-sm leading-6 text-[#71818b]">{meta.description}</p></div>{showNew && <Button onClick={onNew} className="h-11 rounded-xl bg-[#ef6c4d] text-white hover:bg-[#df5c3d]"><Plus className="mr-2 h-4 w-4" />New entry</Button>}</div>;
}

function SelectField({ label, value, onChange, options, disabled = false }: { label: string; value: string; onChange: React.ChangeEventHandler<HTMLSelectElement>; options: readonly (string | { label: string; value: string })[]; disabled?: boolean }) {
  return <div><Label className="mb-1.5 block text-xs font-semibold text-[#516a74]">{label}</Label><div className="relative"><select disabled={disabled} value={value} onChange={onChange} className="h-10 w-full appearance-none rounded-lg border border-[#dbe6e8] bg-white px-3 pr-8 text-sm text-[#516a74] outline-none focus:border-[#79b9b0] focus:ring-2 focus:ring-[#d8eeea]">{options.map(option => typeof option === "string" ? <option key={option} value={option}>{option}</option> : <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#97a7ad]" /></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="mb-1.5 block text-xs font-semibold text-[#516a74]">{label}</Label>{children}</div>; }
function Empty({ title, copy, action, onAction }: { title: string; copy: string; action?: string; onAction?: () => void }) { return <div className="rounded-2xl border border-dashed border-[#d4e1e3] bg-[#fbfdfd] px-5 py-10 text-center"><Check className="mx-auto mb-3 h-7 w-7 text-[#8fb5af]" /><p className="text-sm font-semibold text-[#163247]">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#8a9aa1]">{copy}</p>{action && <Button onClick={onAction} variant="outline" className="mt-4 rounded-lg border-[#cbdedd] text-[#1d665e]">{action}</Button>}</div>; }
function Layout({ children }: { children: React.ReactNode }) { return <div className="mx-auto max-w-[1200px]">{children}</div>; }

function AttendancePage() {
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ employeeId: "", employeeRole: "Factory Staff", attendanceDate: todayInput(), status: "PRESENT" as "PRESENT" | "ABSENT" | "LATE" | "LEAVE", checkInTime: "08:00", remarks: "" });
  const users = trpc.phase2.staff.useQuery();
  const rows = trpc.phase2.attendance.list.useQuery({ date: todayInput() });
  const summary = trpc.phase2.attendance.summary.useQuery({ date: todayInput() });
  const utils = trpc.useUtils();
  const save = trpc.phase2.attendance.save.useMutation({ onSuccess: () => { toast.success("Attendance saved"); setShowForm(false); utils.phase2.attendance.list.invalidate(); utils.phase2.attendance.summary.invalidate(); utils.phase2.dashboard.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="attendance" onNew={() => setShowForm(v => !v)} /><div className="mb-6 grid gap-3 grid-cols-2 lg:grid-cols-5">{[["Present", summary.data?.present, "metric-teal"], ["Absent", summary.data?.absent, "metric-red"], ["Late", summary.data?.late, "metric-orange"], ["Leave", summary.data?.leave, "metric-blue"], ["Total manpower", summary.data?.total, "metric-teal"]].map(([label, value, tone]) => <div key={label as string} className="metric-card rounded-2xl p-4"><p className="text-xs text-[#71818b]">{label as string}</p><p className={`mt-1 text-2xl font-bold ${tone === "metric-red" ? "text-[#d46355]" : "text-[#163247]"}`}>{number(value)}</p></div>)}</div>{showForm && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader className="flex flex-row items-center justify-between border-b border-[#e4efed] px-5 py-4"><div><CardTitle className="text-base text-[#163247]">Record attendance</CardTitle><p className="mt-1 text-xs text-[#82969a]">Manager and owner access only.</p></div><Button variant="ghost" size="icon" onClick={() => setShowForm(false)}><X className="h-4 w-4" /></Button></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><SelectField label="Employee" value={form.employeeId} onChange={e => { const selected = users.data?.find(user => user.id === Number(e.target.value)); setForm({ ...form, employeeId: e.target.value, employeeRole: selected?.role === "manager" ? "Manager" : selected?.role === "owner" ? "Owner" : "Factory Staff" }); }} options={users.data?.map(user => ({ label: `${user.name || "Unnamed"} · ${user.role}`, value: String(user.id) })) ?? []} /><Field label="Date"><Input type="date" value={form.attendanceDate} onChange={e => setForm({ ...form, attendanceDate: e.target.value })} /></Field><SelectField label="Status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })} options={["PRESENT", "ABSENT", "LATE", "LEAVE"]} /><Field label="Check-in time"><Input type="time" value={form.checkInTime} onChange={e => setForm({ ...form, checkInTime: e.target.value })} /></Field><div className="sm:col-span-2 lg:col-span-4"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} placeholder="Shift notes…" /></Field></div><div className="flex justify-end gap-2 sm:col-span-2 lg:col-span-4"><Button variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={save.isPending || !form.employeeId} onClick={() => save.mutate({ ...form, employeeId: Number(form.employeeId), checkInTime: form.status === "ABSENT" || form.status === "LEAVE" ? null : form.checkInTime })} className="bg-[#1d7d73] text-white hover:bg-[#155c55]">{save.isPending ? "Saving…" : "Save attendance"}</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee] shadow-[0_8px_30px_rgba(28,63,77,0.04)]"><CardHeader><CardTitle className="text-base text-[#163247]">Today’s attendance</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <div key={row.attendance.id} className="customer-row"><div className="customer-avatar">{(row.employeeName || "U").slice(0, 1).toUpperCase()}</div><div className="flex-1"><p className="text-sm font-semibold text-[#163247]">{row.employeeName || "Unnamed staff"}</p><p className="mt-1 text-xs text-[#829198]">{row.attendance.employeeRole} · {row.attendance.checkInTime ? dateTime(row.attendance.checkInTime) : "No check-in time"}</p></div><span className={`status-badge ${row.attendance.status === "PRESENT" ? "status-success" : row.attendance.status === "LATE" ? "status-teal" : "status-danger"}`}>{row.attendance.status}</span></div>) : <Empty title="No attendance recorded today" copy="Start with the floor team’s attendance so the dashboard manpower numbers stay current." action="Record attendance" onAction={() => setShowForm(true)} />}</CardContent></Card>
  </Layout>;
}

function OrderPicker({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const orders = trpc.orders.list.useQuery();
  return <SelectField label="Order" value={value} onChange={e => onChange(e.target.value)} options={orders.data?.map(row => ({ label: `${row.order.orderCode} · ${row.order.product}`, value: String(row.order.id) })) ?? []} />;
}
function EntryCard({ title, subtitle, children, badge }: { title: string; subtitle: string; children: React.ReactNode; badge?: string }) { return <div className="order-card"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[#163247]">{title}</p>{badge && <span className="status-badge status-teal">{badge}</span>}</div><p className="mt-1 text-xs text-[#7d9098]">{subtitle}</p></div>{children}</div>; }

function CuttingPage() {
  const [show, setShow] = useState(false); const [form, setForm] = useState({ orderId: "", cuttingTarget: 0, cutQuantity: 0, cuttingDate: todayInput(), cuttingStaffId: "", fabricReceivedQuantity: 0, fabricIssuedQuantity: 0, status: "IN PROGRESS" as "PENDING" | "IN PROGRESS" | "COMPLETED", remarks: "" });
  const users = trpc.phase2.staff.useQuery(); const rows = trpc.phase2.cutting.list.useQuery(); const utils = trpc.useUtils();
  const save = trpc.phase2.cutting.create.useMutation({ onSuccess: result => { toast.success(`Cutting saved · ${number(result.remaining)} remaining`); setShow(false); utils.phase2.cutting.list.invalidate(); utils.phase2.pipeline.invalidate(); utils.phase2.dashboard.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="cutting" onNew={() => setShow(v => !v)} />{show && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader><CardTitle className="text-base text-[#163247]">New cutting entry</CardTitle></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><OrderPicker value={form.orderId} onChange={orderId => setForm({ ...form, orderId })} /><Field label="Cutting target"><Input type="number" min="0" value={form.cuttingTarget || ""} onChange={e => setForm({ ...form, cuttingTarget: Number(e.target.value) })} /></Field><Field label="Cut quantity"><Input type="number" min="0" value={form.cutQuantity || ""} onChange={e => setForm({ ...form, cutQuantity: Number(e.target.value) })} /></Field><Field label="Cutting date"><Input type="date" value={form.cuttingDate} onChange={e => setForm({ ...form, cuttingDate: e.target.value })} /></Field><SelectField label="Cutting staff" value={form.cuttingStaffId} onChange={e => setForm({ ...form, cuttingStaffId: e.target.value })} options={users.data?.map(user => ({ label: user.name || "Unnamed", value: String(user.id) })) ?? []} /><SelectField label="Status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })} options={["PENDING", "IN PROGRESS", "COMPLETED"]} /><Field label="Fabric received"><Input type="number" min="0" value={form.fabricReceivedQuantity || ""} onChange={e => setForm({ ...form, fabricReceivedQuantity: Number(e.target.value) })} /></Field><Field label="Fabric issued"><Input type="number" min="0" value={form.fabricIssuedQuantity || ""} onChange={e => setForm({ ...form, fabricIssuedQuantity: Number(e.target.value) })} /></Field><div className="sm:col-span-2 lg:col-span-4"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} /></Field></div><div className="flex justify-end gap-2 sm:col-span-2 lg:col-span-4"><Button variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={save.isPending || !form.orderId} onClick={() => save.mutate({ ...form, orderId: Number(form.orderId), cuttingTarget: Number(form.cuttingTarget), cutQuantity: Number(form.cutQuantity), cuttingStaffId: form.cuttingStaffId ? Number(form.cuttingStaffId) : undefined, fabricReceivedQuantity: Number(form.fabricReceivedQuantity), fabricIssuedQuantity: Number(form.fabricIssuedQuantity) })} className="bg-[#1d7d73] text-white">{save.isPending ? "Saving…" : "Save cutting"}</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee]"><CardHeader><CardTitle className="text-base text-[#163247]">Cutting history</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <EntryCard key={row.entry.id} title={`${row.orderCode} · ${row.product}`} subtitle={`${displayDate(row.entry.cuttingDate)} · ${row.staffName || "Staff"} · ${number(row.entry.cutQuantity)} cut of ${number((row.orderQuantity ?? 0))} pcs`} badge={row.entry.status}><span className="text-sm font-bold text-[#1d7d73]">{Math.round((row.entry.cutQuantity / (row.orderQuantity ?? 0)) * 100)}%</span></EntryCard>) : <Empty title="No cutting entries yet" copy="The cutting stage will appear here as soon as fabric is cut for an order." action="Add cutting" onAction={() => setShow(true)} />}</CardContent></Card>
  </Layout>;
}

function PrintingPage() {
  const [show, setShow] = useState(false); const [form, setForm] = useState({ orderId: "", printType: "DTF", designReference: "", printingTarget: 0, printedQuantity: 0, rejectedQuantity: 0, printingDate: todayInput(), printingStaffId: "", status: "IN PROGRESS" as "PENDING" | "IN PROGRESS" | "COMPLETED", remarks: "" });
  const users = trpc.phase2.staff.useQuery(); const rows = trpc.phase2.printing.list.useQuery(); const utils = trpc.useUtils();
  const save = trpc.phase2.printing.create.useMutation({ onSuccess: result => { toast.success(`Printing saved · ${number(result.goodQuantity)} good printed`); setShow(false); utils.phase2.printing.list.invalidate(); utils.phase2.pipeline.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="printing" onNew={() => setShow(v => !v)} />{show && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader><CardTitle className="text-base text-[#163247]">New DTF printing entry</CardTitle><p className="mt-1 text-xs text-[#82969a]">Orders not marked as DTF-required are blocked from printing entries.</p></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><OrderPicker value={form.orderId} onChange={orderId => setForm({ ...form, orderId })} /><Field label="Print type"><Input value={form.printType} onChange={e => setForm({ ...form, printType: e.target.value })} /></Field><Field label="Design / reference"><Input value={form.designReference} onChange={e => setForm({ ...form, designReference: e.target.value })} /></Field><Field label="Printing date"><Input type="date" value={form.printingDate} onChange={e => setForm({ ...form, printingDate: e.target.value })} /></Field><Field label="Printing target"><Input type="number" min="0" value={form.printingTarget || ""} onChange={e => setForm({ ...form, printingTarget: Number(e.target.value) })} /></Field><Field label="Printed quantity"><Input type="number" min="0" value={form.printedQuantity || ""} onChange={e => setForm({ ...form, printedQuantity: Number(e.target.value) })} /></Field><Field label="Rejected quantity"><Input type="number" min="0" value={form.rejectedQuantity || ""} onChange={e => setForm({ ...form, rejectedQuantity: Number(e.target.value) })} /></Field><SelectField label="Printing staff" value={form.printingStaffId} onChange={e => setForm({ ...form, printingStaffId: e.target.value })} options={users.data?.map(user => ({ label: user.name || "Unnamed", value: String(user.id) })) ?? []} /><SelectField label="Status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })} options={["PENDING", "IN PROGRESS", "COMPLETED", "NOT REQUIRED"]} /><div className="sm:col-span-2 lg:col-span-3"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} /></Field></div><div className="flex items-end justify-end gap-2"><Button variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={save.isPending || !form.orderId} onClick={() => save.mutate({ ...form, orderId: Number(form.orderId), printingTarget: Number(form.printingTarget), printedQuantity: Number(form.printedQuantity), rejectedQuantity: Number(form.rejectedQuantity), printingStaffId: form.printingStaffId ? Number(form.printingStaffId) : undefined })} className="bg-[#1d7d73] text-white">Save printing</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee]"><CardHeader><CardTitle className="text-base text-[#163247]">DTF history</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <EntryCard key={row.entry.id} title={`${row.orderCode} · ${row.product}`} subtitle={`${displayDate(row.entry.printingDate)} · ${row.staffName || "Staff"} · ${number(row.entry.printedQuantity - row.entry.rejectedQuantity)} good printed`} badge={row.entry.status}><span className="text-sm font-bold text-[#1d7d73]">{(row.orderQuantity ?? 0) ? Math.round(((row.entry.printedQuantity - row.entry.rejectedQuantity) / (row.orderQuantity ?? 0)) * 100) : 0}%</span></EntryCard>) : <Empty title="No DTF entries yet" copy="DTF is optional. Mark an order as printing-required from Orders before recording output." action="Add printing" onAction={() => setShow(true)} />}</CardContent></Card>
  </Layout>;
}

function QcPage() {
  const [show, setShow] = useState(false); const [form, setForm] = useState({ orderId: "", qcDate: todayInput(), checkedQuantity: 0, passedQuantity: 0, failedQuantity: 0, reworkQuantity: 0, qcStaffId: "", defectType: "", status: "PASSED" as "PENDING" | "IN PROGRESS" | "PASSED" | "REWORK REQUIRED" | "FAILED", remarks: "" });
  const users = trpc.phase2.staff.useQuery(); const rows = trpc.phase2.qc.list.useQuery(); const utils = trpc.useUtils(); const save = trpc.phase2.qc.create.useMutation({ onSuccess: result => { toast.success(`QC saved · ${result.passRate}% pass rate`); setShow(false); utils.phase2.qc.list.invalidate(); utils.phase2.pipeline.invalidate(); utils.phase2.dashboard.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="qc" onNew={() => setShow(v => !v)} />{show && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader><CardTitle className="text-base text-[#163247]">New QC check</CardTitle><p className="mt-1 text-xs text-[#82969a]">Passed + failed cannot exceed checked. Rework is a subset of failed.</p></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><OrderPicker value={form.orderId} onChange={orderId => setForm({ ...form, orderId })} /><Field label="QC date"><Input type="date" value={form.qcDate} onChange={e => setForm({ ...form, qcDate: e.target.value })} /></Field><Field label="Checked quantity"><Input type="number" min="0" value={form.checkedQuantity || ""} onChange={e => setForm({ ...form, checkedQuantity: Number(e.target.value) })} /></Field><Field label="Passed quantity"><Input type="number" min="0" value={form.passedQuantity || ""} onChange={e => setForm({ ...form, passedQuantity: Number(e.target.value) })} /></Field><Field label="Failed quantity"><Input type="number" min="0" value={form.failedQuantity || ""} onChange={e => setForm({ ...form, failedQuantity: Number(e.target.value) })} /></Field><Field label="Rework quantity"><Input type="number" min="0" value={form.reworkQuantity || ""} onChange={e => setForm({ ...form, reworkQuantity: Number(e.target.value) })} /></Field><SelectField label="QC staff" value={form.qcStaffId} onChange={e => setForm({ ...form, qcStaffId: e.target.value })} options={users.data?.map(user => ({ label: user.name || "Unnamed", value: String(user.id) })) ?? []} /><SelectField label="Status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })} options={["PENDING", "IN PROGRESS", "PASSED", "REWORK REQUIRED", "FAILED"]} /><Field label="Defect type"><Input value={form.defectType} onChange={e => setForm({ ...form, defectType: e.target.value })} placeholder="Print, stitching, measurement…" /></Field><div className="sm:col-span-2"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} /></Field></div><div className="flex items-end justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={save.isPending || !form.orderId} onClick={() => save.mutate({ ...form, orderId: Number(form.orderId), checkedQuantity: Number(form.checkedQuantity), passedQuantity: Number(form.passedQuantity), failedQuantity: Number(form.failedQuantity), reworkQuantity: Number(form.reworkQuantity), qcStaffId: form.qcStaffId ? Number(form.qcStaffId) : undefined })} className="bg-[#1d7d73] text-white">Save QC</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee]"><CardHeader><CardTitle className="text-base text-[#163247]">QC history</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <EntryCard key={row.entry.id} title={`${row.orderCode} · ${row.product}`} subtitle={`${displayDate(row.entry.qcDate)} · ${number(row.entry.checkedQuantity)} checked · ${number(row.entry.failedQuantity)} failed · ${number(row.entry.reworkQuantity)} rework`} badge={row.entry.status}><span className="text-sm font-bold text-[#1d7d73]">{row.entry.checkedQuantity ? Math.round((row.entry.passedQuantity / row.entry.checkedQuantity) * 100) : 0}% pass</span></EntryCard>) : <Empty title="No QC checks yet" copy="Quality checks will make failed and rework quantities visible to the whole team." action="Add QC check" onAction={() => setShow(true)} />}</CardContent></Card>
  </Layout>;
}

function PackingPage() {
  const [show, setShow] = useState(false); const [form, setForm] = useState({ orderId: "", packingTarget: 0, packedQuantity: 0, packingDate: todayInput(), packingStaffId: "", status: "IN PROGRESS" as "PENDING" | "IN PROGRESS" | "COMPLETED", remarks: "" }); const users = trpc.phase2.staff.useQuery(); const rows = trpc.phase2.packing.list.useQuery(); const utils = trpc.useUtils(); const save = trpc.phase2.packing.create.useMutation({ onSuccess: result => { toast.success(`Packing saved · ${number(result.remaining)} remaining`); setShow(false); utils.phase2.packing.list.invalidate(); utils.phase2.pipeline.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="packing" onNew={() => setShow(v => !v)} />{show && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader><CardTitle className="text-base text-[#163247]">New packing entry</CardTitle></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><OrderPicker value={form.orderId} onChange={orderId => setForm({ ...form, orderId })} /><Field label="Packing target"><Input type="number" min="0" value={form.packingTarget || ""} onChange={e => setForm({ ...form, packingTarget: Number(e.target.value) })} /></Field><Field label="Packed quantity"><Input type="number" min="0" value={form.packedQuantity || ""} onChange={e => setForm({ ...form, packedQuantity: Number(e.target.value) })} /></Field><Field label="Packing date"><Input type="date" value={form.packingDate} onChange={e => setForm({ ...form, packingDate: e.target.value })} /></Field><SelectField label="Packing staff" value={form.packingStaffId} onChange={e => setForm({ ...form, packingStaffId: e.target.value })} options={users.data?.map(user => ({ label: user.name || "Unnamed", value: String(user.id) })) ?? []} /><SelectField label="Status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })} options={["PENDING", "IN PROGRESS", "COMPLETED"]} /><div className="sm:col-span-2"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} /></Field></div><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={save.isPending || !form.orderId} onClick={() => save.mutate({ ...form, orderId: Number(form.orderId), packingTarget: Number(form.packingTarget), packedQuantity: Number(form.packedQuantity), packingStaffId: form.packingStaffId ? Number(form.packingStaffId) : undefined })} className="bg-[#1d7d73] text-white">Save packing</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee]"><CardHeader><CardTitle className="text-base text-[#163247]">Packing history</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <EntryCard key={row.entry.id} title={`${row.orderCode} · ${row.product}`} subtitle={`${displayDate(row.entry.packingDate)} · ${number(row.entry.packedQuantity)} packed of ${number((row.orderQuantity ?? 0))} pcs`} badge={row.entry.status}><span className="text-sm font-bold text-[#1d7d73]">{Math.round((row.entry.packedQuantity / (row.orderQuantity ?? 0)) * 100)}%</span></EntryCard>) : <Empty title="No packing entries yet" copy="Packing progress will feed the delivery stage automatically." action="Add packing" onAction={() => setShow(true)} />}</CardContent></Card>
  </Layout>;
}

function DeliveryPage() {
  const [show, setShow] = useState(false); const [form, setForm] = useState({ orderId: "", deliveryDate: todayInput(), deliveredQuantity: 0, deliveryStatus: "PARTIALLY DELIVERED" as "READY" | "PARTIALLY DELIVERED" | "DELIVERED", receiverCustomer: "", deliveryNote: "", remarks: "" }); const rows = trpc.phase2.delivery.list.useQuery(); const utils = trpc.useUtils(); const save = trpc.phase2.delivery.create.useMutation({ onSuccess: result => { toast.success(`Delivery saved · ${number(result.remaining)} remaining`); setShow(false); utils.phase2.delivery.list.invalidate(); utils.phase2.pipeline.invalidate(); utils.orders.list.invalidate(); }, onError: e => toast.error(e.message) });
  return <Layout><Header module="delivery" onNew={() => setShow(v => !v)} />{show && <Card className="mb-6 border-[#cfe4e0] bg-[#fbfefd]"><CardHeader><CardTitle className="text-base text-[#163247]">Record delivery</CardTitle><p className="mt-1 text-xs text-[#82969a]">DELIVERED is accepted only when the full order quantity is delivered.</p></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><OrderPicker value={form.orderId} onChange={orderId => setForm({ ...form, orderId })} /><Field label="Delivery date"><Input type="date" value={form.deliveryDate} onChange={e => setForm({ ...form, deliveryDate: e.target.value })} /></Field><Field label="Delivered quantity"><Input type="number" min="0" value={form.deliveredQuantity || ""} onChange={e => setForm({ ...form, deliveredQuantity: Number(e.target.value) })} /></Field><SelectField label="Delivery status" value={form.deliveryStatus} onChange={e => setForm({ ...form, deliveryStatus: e.target.value as any })} options={["READY", "PARTIALLY DELIVERED", "DELIVERED"]} /><Field label="Receiver / customer"><Input value={form.receiverCustomer} onChange={e => setForm({ ...form, receiverCustomer: e.target.value })} /></Field><Field label="Delivery note"><Input value={form.deliveryNote} onChange={e => setForm({ ...form, deliveryNote: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Remarks"><Textarea value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })} /></Field></div><div className="flex justify-end gap-2 sm:col-span-2 lg:col-span-4"><Button variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={save.isPending || !form.orderId} onClick={() => save.mutate({ ...form, orderId: Number(form.orderId), deliveredQuantity: Number(form.deliveredQuantity) })} className="bg-[#1d7d73] text-white">Save delivery</Button></div></CardContent></Card>}
    <Card className="border-[#e2ecee]"><CardHeader><CardTitle className="text-base text-[#163247]">Delivery history</CardTitle></CardHeader><CardContent className="space-y-2">{rows.data?.length ? rows.data.map(row => <EntryCard key={row.entry.id} title={`${row.orderCode} · ${row.product}`} subtitle={`${displayDate(row.entry.deliveryDate)} · ${number(row.entry.deliveredQuantity)} delivered · ${row.entry.receiverCustomer || "Receiver not recorded"}`} badge={row.entry.deliveryStatus}><Truck className="h-4 w-4 text-[#1d7d73]" /></EntryCard>) : <Empty title="No deliveries recorded" copy="Delivery entries will update the order pipeline and remaining quantity." action="Record delivery" onAction={() => setShow(true)} />}</CardContent></Card>
  </Layout>;
}

export default function Phase2Page({ module }: { module: Module }) {
  if (module === "attendance") return <AttendancePage />;
  if (module === "cutting") return <CuttingPage />;
  if (module === "printing") return <PrintingPage />;
  if (module === "qc") return <QcPage />;
  if (module === "packing") return <PackingPage />;
  return <DeliveryPage />;
}
